### ISSUE TITLE
Doesn't work for folder with a / in the name

### ISSUE THREAD

**Issue by polytan02** [KyleWJohnston/outlook-move-to-thread#3]
Hello,

The macro works really well, apart on one folder.
I named it "IT / Expenses / Finance / Training" (without the " " ) and for some reasons, the macro fails.

**Comment by k4j8** [comment]
It may have to do with how the macro converts folder path strings to a folder object, although that relies on "\\" (backslash) rather than "/" (forward slash).

Does removing the slashes fix your issue? If so, I can add a fix.

If not, can you paste debug info from the Immediate Windows? It can be accessed within the VBA editor under the View menu or with the shortcut Ctrl+G.

**Comment by k4j8** [comment]
Never mind, I was able to replicate. All folder strings are converted to ASCII characters, which does not include a forward slash. This causes `GetFolder` to return a bad value. I'll need to find a way to convert the existing folders to ASCII or convert the target folder to a normal string.

In the meantime, the workaround is to only use ASCII characters.

**Comment by polytan02** [comment]
For me it is not the the of the world, I will rename the folders.

Maybe we could add a note on the readme in the meantime ?

**Comment by k4j8** [comment]
Commit 042a83ba5479fe3bd4d38b5556bd640cb8bee287 references this issue in the README. I'll leave this as an open bug until I can get around to fixing it, as slashes and other characters should be supported.

**Comment by grrhendra** [comment]
I was able to fix this as follows:

1. Insert the line `FolderPath = Replace(fld.FolderPath, "%2F", "/")` after the two `Set fld = obj.Parent` lines
2. Replace all instances of `fld.FolderPath` (except those added in step 1) with `FolderPath`

I haven't tested it extensively, but it worked for the one thread that brought this problem to my attention.

**Comment by k4j8** [comment]
I tested this and it worked for me as well. With this change, the macro should work with most symbols except for "%" and "\". I tried encoding them as well but ran into issues.

I'll update the macro shortly with this fix.
