### ISSUE TITLE
Code hangs

### ISSUE THREAD

**Issue by fireextinguisher** [KyleWJohnston/outlook-move-to-thread#6]
Code hangs at line Set group = theConversation.GetRootItems
Is it compatible with Outlook 2016?

**Comment by k4j8** [comment]
Definitely works with Outlook 2016, that's what I use. Can you check if `theConversation` is defined in the locals window?

**Comment by k4j8** [comment]
I'm getting this issue now too after my Office applications updated to a newer version of Office 2016.

**Comment by fireextinguisher** [comment]
Thank you, for update. Unfortunately, I didn't check if theConversation is defined. Do you think this issue could be resolved?

**Comment by k4j8** [comment]
`theConversation` is defined at that point. Something must have changed with the update. I'll look into it, but I'm not sure when/if I'll be able to fix it. There's not much documentation on this issue.

**Comment by k4j8** [comment]
I haven't had issues with the code hanging in a long time now. Perhaps an update on Microsoft's end fixed it? Please reopen if the issue persists.
